docker:
  image: yegor256/rultor-image:1.22.0
install: |-
  gem install texsc:0.6.0
  gem install texqc:0.6.0
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none install huawei xstring totpages environ hyperxmp ifmtarg ncctools comment biblatex href-ul libertine ffcode
merge:
  script: |-
    make