# SPDX-FileCopyrightText: Copyright (c) 2022 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
install: |-
  sudo "$(pwd)/lecture-notes/tlmgr-install.sh"
merge:
  script: |-
    make
